name: Bloglist deployment pipeline

env:
  PORT: ${{ secrets.PORT }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  frontend_deployment_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bloglist
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Start backend (test mode)
        run: |
          npm run start:testbackend &
          npx wait-on http://localhost:3003/api/testing
      - name: Start frontend
        run: |
          npm run start:frontend &
          npx wait-on http://localhost:5173
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./bloglist
          command: npm run test:e2e